# Generated by Django 6.0.4 on 2026-04-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_productrating_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviews',
            new_name='review',
        ),
    ]
